ボタンのfont-weight変更とリストのビュレットとテキストのpaddingを変更
codeforjapan/CivicTechCC-Website pull request #12
Opened 2020-07-15 14:48 UTC by kota-yata

![image](https://user-images.githubusercontent.com/51294895/87559431-411e1880-c6f5-11ea-9fc8-802168f1807d.png)
モバイルで見にくいためボタンのテキストを太字に変更。

![image](https://user-images.githubusercontent.com/51294895/87559395-32376600-c6f5-11ea-9058-680953bcc4aa.png)
ビュレットの位置を変更

close #8

2020-07-15 14:51 UTC, Nekoya3 commented
コンフリクト解消よろしくお願いします！！

2020-07-16 01:51 UTC, MaySoMusician requested changes

2020-07-16 01:51 UTC, MaySoMusician commented on components/GuideLine.vue
> +
エントリーボタンをいじりたい場合は最新の `ButtonEntry.vue` を調整すれば2個とも変わる

2020-07-16 12:15 UTC, kota-yata commented
Default.vueとGuideline.vue両方のCSSを変更していたのをButtonEntry.vueでまとめて変更しました。

2020-07-16 12:57 UTC, NEKOYASAN approved these changes
LGTM

2020-07-16 12:57 UTC, merged