Twitterシェアボタンとハッシュタグの追加
codeforjapan/CivicTechCC-Website pull request #30
Opened 2020-07-29 15:00 UTC by y-chan

デザインが適当すぎるのでどしどし案が欲しい

2020-07-29 17:13 UTC, MaySoMusician commented on components/TwitterShare.vue
> +    <v-btn rounded color="#00acee" class="ShareButton" @click="twitter">
```suggestion
    <v-btn
      rounded
      color="#1DA1F2"
      class="ShareButton"
      href="https://twitter.com/intent/tweet?text=Civictech%20Challenge%20Cup%20U-22&url=https://ccc2020.code4japan.org&hashtags=CCCu22"
      target="noopener noreferrer"
    >
```

一応Twitterの色は `#1DA1F2` ということになってる（[この資料の p.8 参照](https://about.twitter.com/content/dam/about-twitter/company/brand-resources/en_us/Twitter_Brand_Guidelines_V2_0.pdf)）

2020-07-29 17:14 UTC, MaySoMusician commented
デザインは、もっと大きくして画面中央揃えでも良いかと

2020-07-31 07:26 UTC, y-chan commented
中央揃え&大きくしました
PC
![image](https://user-images.githubusercontent.com/34832037/89010710-16b19980-d34a-11ea-96b7-401fe286169b.png)
スマホ
![image](https://user-images.githubusercontent.com/34832037/89010758-2b8e2d00-d34a-11ea-97f7-a8d3a5e6d9ae.png)

2020-08-02 10:10 UTC, NEKOYASAN requested changes
確認ください

2020-08-02 10:10 UTC, NEKOYASAN commented on components/TwitterShare.vue
> +        target="noopener noreferrer"
```suggestion
        target="_blank"
        rel="noopener noreferrer"
```

では？

2020-08-02 10:10 UTC, NEKOYASAN commented on components/TwitterShare.vue
> +  }
上でそろえるのではなく、上下中央揃えのほうが今のデザインでいくのであればよいと思う

2020-08-02 10:10 UTC, NEKOYASAN commented on components/TwitterShare.vue
> +        <img src="/twitter.svg" width="20" alt="twitter" />
Twitterアイコンの左右のクリアランスが足りてないのでブランドガイドラインに違反してる

2020-08-03 15:39 UTC, MaySoMusician commented on components/TwitterShare.vue
> +        target="noopener noreferrer"
これは俺がsuggestしたときにミスってたかも

2020-08-07 12:52 UTC, NEKOYASAN approved these changes
LGTM to Me!

2020-08-07 14:29 UTC, y-chan commented
LGTMです、マージしますね

2020-08-07 16:02 UTC, merged